version: '3.9'
services:
  mysql:
    hostname: mysql
    image: 'mysql:latest'
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: cats
  service:
    image: cats-project
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cats
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
    depends_on:
      mysql:
        condition: service_started